import Navbar from './components/Navbar/index'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Anime Iyom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-owned-accent`}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
